name: Nx Affected CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        package_manager:
          - yarn
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: yarn install
      - name: Run Affected Tests
        shell: bash
        run: yarn affected:test -- --base=remotes/origin/master --head=HEAD
      - name: Deploy to Netlify
        shell: bash
        if: github.ref == 'refs/heads/master'
        run: NETLIFY_TOKEN=tHInavUB4ywYxyyFWCxUd0N0OvBLJ5xCoSFjtxTZ310 yarn affected:deploy --base=master~1 --head=master

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Execute tests
#        run: exit 0
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    if: github.ref == 'refs/heads/master'
#    steps:
#      - name: Deploy app
#        run: exit 0
